name: CI

on:
  pull_request:
    paths:
      - 'source/**'
      - 'buildtools/**'
      - '.github/workflows/**'
  push:
    paths:
      - 'source/**'
      - 'buildtools/**'
      - '.github/workflows/**'
    branches:
      - 'v**'
    tags:
      - 'v**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            sdcc binutils make curl cpm
      - name: Install M80
        env:
          VERSION: 1.1
        run: |
          curl -Lo m80.zip https://github.com/Konamiman/M80dotNet/releases/download/v${VERSION}/M80dotNet_${VERSION}_SelfContained_linux_x64.zip
          unzip m80.zip
          for NAME in M80 L80 LIB80; do
            sudo install -v ${NAME} /usr/local/bin
            rm ${NAME}
          done
          rm m80.zip
      - name: Add buildtools
        run: |
          for NAME in buildtools/linux/*; do
            sudo install -v ${NAME} /usr/local/bin
          done
      - name: Make all
        run: make -C source
